export const POWERPLAY_OPTIONS = {
  powerplay: {
    value: 'powerplay',
    viewValue: 'Powerplay',
  },
  death: {
    value: 'death',
    viewValue: 'Death',
  },
  all: {
    value: 'all',
    viewValue: 'All',
  },
};

export const FORMAT_OPTIONS = {
  T20: {
    value: 'T20',
    viewValue: 'T20',
  },
  ODI: {
    value: 'ODI',
    viewValue: 'ODI',
  },
};
export const TYPE_OPTIONS = {
  official: {
    value: 'official',
    viewValue: 'Official',
  },
  practice: {
    value: 'practice',
    viewValue: 'Practice',
  },
};

export const TABLE_CONFIGS = {
  tableT20AllOvers: {
    powerplay: 'all',
    format: 'T20',
    type: 'official',
    sortBy: 'wickets',
  },
  tableT20PowerPlay: {
    powerplay: 'powerplay',
    format: 'T20',
    type: 'official',
    sortBy: 'wickets',
  },
  tableT20Death: {
    powerplay: 'death',
    format: 'T20',
    type: 'official',
    sortBy: 'wickets',
  },
  tableOdiAllOvers: {
    powerplay: 'all',
    format: 'ODI',
    type: 'official',
    sortBy: 'wickets',
  },
  tableOdiPowerPlay: {
    powerplay: 'powerplay',
    format: 'ODI',
    type: 'official',
    sortBy: 'wickets',
  },
  tableOdiDeath: {
    powerplay: 'death',
    format: 'ODI',
    type: 'official',
    sortBy: 'wickets',
  },
};
export const CHART_CONFIGS = {
  T20: {
    powerplay: {
      powerplay: 'powerplay',
      format: 'T20',
      type: 'official',
      sortBy: 'bowlerName',
      chartType: 'bar',
      dataPoints: [
        { name: 'Wickets', property: 'wickets' },
        { name: 'Average', property: 'average' },
        { name: 'Economy', property: 'economy' },
      ],
    },
    death: {
      powerplay: 'death',
      format: 'T20',
      type: 'official',
      sortBy: 'bowlerName',
      chartType: 'bar',
      dataPoints: [
        { name: 'Wickets', property: 'wickets' },
        { name: 'Average', property: 'average' },
        { name: 'Economy', property: 'economy' },
      ],
    },
    all: {
      powerplay: 'all',
      format: 'T20',
      type: 'official',
      sortBy: 'bowlerName',
      chartType: 'bar',
      dataPoints: [
        { name: 'Wickets', property: 'wickets' },
        { name: 'Average', property: 'average' },
        { name: 'Economy', property: 'economy' },
      ],
    },
    widesAll: {
      powerplay: 'all',
      format: 'T20',
      type: 'official',
      sortBy: 'wides',
      chartType: 'bar',
      dataPoints: [{ name: 'Wides', property: 'wides' }],
    },
    noBallsAll: {
      powerplay: 'all',
      format: 'T20',
      type: 'official',
      sortBy: 'noBalls',
      chartType: 'bar',
      dataPoints: [{ name: 'No Balls', property: 'noBalls' }],
    },
    widesPowerPlay: {
      powerplay: 'powerplay',
      format: 'T20',
      type: 'official',
      sortBy: 'wides',
      chartType: 'bar',
      dataPoints: [{ name: 'Wides', property: 'wides' }],
    },
    noBallsPowerPlay: {
      powerplay: 'powerplay',
      format: 'T20',
      type: 'official',
      sortBy: 'noBalls',
      chartType: 'bar',
      dataPoints: [{ name: 'No Balls', property: 'noBalls' }],
    },
    widesDeath: {
      powerplay: 'death',
      format: 'T20',
      type: 'official',
      sortBy: 'wides',
      chartType: 'bar',
      dataPoints: [{ name: 'Wides', property: 'wides' }],
    },
    noBallsDeath: {
      powerplay: 'death',
      format: 'T20',
      type: 'official',
      sortBy: 'noBalls',
      chartType: 'bar',
      dataPoints: [{ name: 'No Balls', property: 'noBalls' }],
    },
    runsInPowerPlay: {
      powerplay: 'powerplay',
      format: 'T20',
      type: 'official',
      sortBy: 'runs',
      chartType: 'bar',
      dataPoints: [{ name: 'Runs', property: 'runs' }],
    },
    runsInDeath: {
      powerplay: 'death',
      format: 'T20',
      type: 'official',
      sortBy: 'runs',
      chartType: 'bar',
      dataPoints: [{ name: 'Runs', property: 'runs' }],
    },
    runsInAll: {
      powerplay: 'all',
      format: 'T20',
      type: 'official',
      sortBy: 'runs',
      chartType: 'bar',
      dataPoints: [{ name: 'Runs', property: 'runs' }],
    },
    wicketsInPowerPlay: {
      powerplay: 'powerplay',
      format: 'T20',
      type: 'official',
      sortBy: 'wickets',
      chartType: 'bar',
      dataPoints: [{ name: 'Wickets', property: 'wickets' }],
    },
    wicketsInDeath: {
      powerplay: 'death',
      format: 'T20',
      type: 'official',
      sortBy: 'wickets',
      chartType: 'bar',
      dataPoints: [{ name: 'Wickets', property: 'wickets' }],
    },
    wicketsInAll: {
      powerplay: 'all',
      format: 'T20',
      type: 'official',
      sortBy: 'wickets',
      chartType: 'bar',
      dataPoints: [{ name: 'Wickets', property: 'wickets' }],
    },
  },
  ODI: {
    powerplay: {
      powerplay: 'powerplay',
      format: 'ODI',
      type: 'official',
      sortBy: 'bowlerName',
      chartType: 'bar',
      dataPoints: [
        { name: 'Wickets', property: 'wickets' },
        { name: 'Runs', property: 'runs' },
        { name: 'Economy', property: 'economy' },
      ],
    },
    death: {
      powerplay: 'death',
      format: 'ODI',
      type: 'official',
      sortBy: 'bowlerName',
      chartType: 'bar',
      dataPoints: [
        { name: 'Wickets', property: 'wickets' },
        { name: 'Runs', property: 'runs' },
        { name: 'Economy', property: 'economy' },
      ],
    },
    all: {
      powerplay: 'all',
      format: 'ODI',
      type: 'official',
      sortBy: 'bowlerName',
      chartType: 'bar',
      dataPoints: [
        { name: 'Wickets', property: 'wickets' },
        { name: 'Runs', property: 'runs' },
        { name: 'Economy', property: 'economy' },
      ],
    },
    widesAll: {
      powerplay: 'all',
      format: 'ODI',
      type: 'official',
      sortBy: 'wides',
      chartType: 'bar',
      dataPoints: [{ name: 'Wides', property: 'wides' }],
    },
    noBallsAll: {
      powerplay: 'all',
      format: 'ODI',
      type: 'official',
      sortBy: 'noBalls',
      chartType: 'bar',
      dataPoints: [{ name: 'No Balls', property: 'noBalls' }],
    },
    widesPowerPlay: {
      powerplay: 'powerplay',
      format: 'ODI',
      type: 'official',
      sortBy: 'wides',
      chartType: 'bar',
      dataPoints: [{ name: 'Wides', property: 'wides' }],
    },
    noBallsPowerPlay: {
      powerplay: 'powerplay',
      format: 'ODI',
      type: 'official',
      sortBy: 'noBalls',
      chartType: 'bar',
      dataPoints: [{ name: 'No Balls', property: 'noBalls' }],
    },
    widesDeath: {
      powerplay: 'death',
      format: 'ODI',
      type: 'official',
      sortBy: 'wides',
      chartType: 'bar',
      dataPoints: [{ name: 'Wides', property: 'wides' }],
    },
    noBallsDeath: {
      powerplay: 'death',
      format: 'ODI',
      type: 'official',
      sortBy: 'noBalls',
      chartType: 'bar',
      dataPoints: [{ name: 'No Balls', property: 'noBalls' }],
    },
    runsInPowerPlay: {
      powerplay: 'powerplay',
      format: 'ODI',
      type: 'official',
      sortBy: 'runs',
      chartType: 'bar',
      dataPoints: [{ name: 'Runs', property: 'runs' }],
    },
    runsInDeath: {
      powerplay: 'death',
      format: 'ODI',
      type: 'official',
      sortBy: 'runs',
      chartType: 'bar',
      dataPoints: [{ name: 'Runs', property: 'runs' }],
    },
    runsInAll: {
      powerplay: 'all',
      format: 'ODI',
      type: 'official',
      sortBy: 'runs',
      chartType: 'bar',
      dataPoints: [{ name: 'Runs', property: 'runs' }],
    },
    wicketsInPowerPlay: {
      powerplay: 'powerplay',
      format: 'ODI',
      type: 'official',
      sortBy: 'wickets',
      chartType: 'bar',
      dataPoints: [{ name: 'Wickets', property: 'wickets' }],
    },
    wicketsInDeath: {
      powerplay: 'death',
      format: 'ODI',
      type: 'official',
      sortBy: 'wickets',
      chartType: 'bar',
      dataPoints: [{ name: 'Wickets', property: 'wickets' }],
    },
    wicketsInAll: {
      powerplay: 'all',
      format: 'ODI',
      type: 'official',
      sortBy: 'wickets',
      chartType: 'bar',
      dataPoints: [{ name: 'Wickets', property: 'wickets' }],
    },
  },
};
